spring:
  application:
    name: fusion-resume-backend

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:fusionresume
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # H2 Console (for debugging)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Server Configuration
  server:
    port: 8080

# Logging
logging:
  level:
    com.fusionresume: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG